# Python Tutorial for SEM——Basic Python and Numpy

The framework of this tutorial and basic python is copied from the materials used in **Introduction to Data Science** in Tsinghua University, which refers to **CS231** and **CS228** in Stanford University. I also refer to 'Python For Data Analysis' written by Wes McKinney, the initiator of Pandas.

# Introduction before introduction


The application of data centric, computational, and inferential thinking to understand the world(Science) of solve problems(Engineering).

* Physical thinking: Domain Science ← So far, we are here.
* Computational Thinking: Computer Science
* Inferential Thinking: Statistice

Lifecycle for data science:
* Questions raised
* Sampling/extraction
* Wrangling
* Data management with simple modelling
* Feature engineering, learning and optimization
* Repeat the above steps for several times
* Interpretation and visualization(or maybe we give up)

# Introduction

Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (**numpy**, **scipy**, **matplotlib**, **pandas**, etc.) it becomes a powerful environment for scientific computing.

In this tutorial, we will cover:

* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes
* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting
* Matplotlib: Plotting, Subplots, Images
* Scipy: Image Processing, Linear Algebra
* Pandas: DataFrame
* US Baby Names 1880–2010: An example for data analysis

## Python versions matter

**Python 2.x** vs. **Python 3.x**

> Somewhat confusingly, Python 3.x introduced many backwards-incompatible changes to the language, so code written for 2.7 may not work under 3.5 and vice versa. For this class all code will use Python 3.x.

Python 2.7 will **NOT** be maintained past 2020. Check the [official statement](https://python3statement.org/).

> Python 2, thank you for your years of faithful service.

> Python 3, **your time is now**.

You can check your Python version at the command line by running:


```bash
python --version
```

# Before Getting Started

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


## KISS (Keep It Simple, Stupid)
1. Make your code **accessible** at one's first glance
2. Make your code as **short** as possible

## DRY (Don't Repeat Yourself)
1. Avoid repetition
2. Reuse the module with specific functionality in different places

# Basics of Python

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable. As an example, here is an implementation of the classic quicksort algorithm in Python:

In [2]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


## Basic data types

### Numbers

Integers and floats work as you would expect from other languages:

In [3]:
x = 3
print(x, type(x))

3 <class 'int'>


In [4]:
print(x + 1)   # Addition;
print(x - 1)   # Subtraction;
print(x * 2)   # Multiplication;
print(x ** 2)  # Exponentiation;
print(x / 2)
print(x // 2)

4
2
6
9
1.5
1


In [6]:
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"

4
8


In [7]:
y = 2.5
print(type(y)) # Prints "<type 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'float'>
2.5 3.5 5.0 6.25


Note that unlike many languages, Python does not have unary increment (x++) or decrement (x--) operators.

Python also has built-in types for long integers and **complex numbers**; you can find all of the details in the [documentation](https://docs.python.org/2/library/stdtypes.html#numeric-types-int-float-long-complex).

### Booleans

Python implements all of the usual operators for Boolean logic, but uses **English words** rather than symbols (`&&`, `||`, etc.):

In [8]:
# ignore irrelevant variables
t, *_, f = True, False, False, True, False
print(t)
print(f)
print(type(t)) # Prints "<type 'bool'>"

True
False
<class 'bool'>


Now we let's look at the operations:

In [9]:
print(t and f) # Logical AND; t && f
print(t or f)  # Logical OR; t || f
print(not t)   # Logical NOT; 
print(t != f)  # Logical XOR;

False
True
False
True


In [10]:
a, b = 1, 2

a, b = b, a

print(a)
print(b)

2
1


### Strings

In [11]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.

# use single quotation in double quotation, it works vice versa
s = "I am 'single' quotation"
print(s)

print(hello, len(hello))

I am 'single' quotation
hello 5


In [12]:
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"

hello world


In [13]:
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting

print(hw12)  # prints "hello world 12"

# you need not to care about parameter types in this manner
print('{} {} {}'.format(hello, world, 12))

# this also works since python 3.6
print(f'{hello} {world} {12}')

hello world 12
hello world 12
hello world 12


In [14]:
s = 'hello'
print(s[0])
print(s[-1])
print(s[::-1])

h
o
olleh


Manipulate string

In [15]:
s = 'hello, python!'

sl = s.split(',')
print(sl)
print(type(sl))

l = ['hello', ' python!']
print('-'.join(l))

print('o' in s)
print('0' in s)

# characters in string are immutable
s[0] = 'H'

['hello', ' python!']
<class 'list'>
hello- python!
True
False


TypeError: 'str' object does not support item assignment

String objects have a bunch of useful methods; for example:

In [16]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                               # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


You can find a list of all string methods in the [documentation](https://docs.python.org/2/library/stdtypes.html#string-methods).

### Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples.

#### Lists

You can loop over the elements of a list like this:

In [17]:
animals = ['cat', 'dog', 'monkey']

for animal in animals:
    print(animal)

for i in range(len(animals)):
    print(animals[i])

cat
dog
monkey
cat
dog
monkey


List elements can be any type.

In [18]:
fusion = [[4, 5], 2, 1, 3, 'hello']

fusion.append('world')
print(fusion)

print('hello' in fusion)
print([5, 4] in fusion)

[[4, 5], 2, 1, 3, 'hello', 'world']
True
False


If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [19]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
for i in list(enumerate(animals)):
    print(i)

#1: cat
#2: dog
#3: monkey
(0, 'cat')
(1, 'dog')
(2, 'monkey')


**List comprehensions**

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [20]:
nums = [0, 1, 2, 3, 4]
squares = list()
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


You can make this code simpler using a list comprehension:

In [21]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


List comprehensions can also contain conditions:

In [22]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


#### Dictionaries

A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

In [23]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

cute
True


In [24]:
d['fish'] = 'wet'    # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"

wet


In [14]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

KeyError: 'monkey'

In [25]:
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"

N/A
wet


In [26]:
del d['fish']        # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

N/A


You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/2/library/stdtypes.html#dict).

It is easy to iterate over the keys in a dictionary:

In [27]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


If you want access to keys and their corresponding values, use the items method:

In [28]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [29]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


#### Sets

A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [30]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"


True
False


In [31]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # Number of elements in a set;

True
3


In [32]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(len(animals))       
animals.remove('cat')    # Remove an element from a set
print(len(animals))       

3
2


_Loops_: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [33]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

#1: fish
#2: cat
#3: dog


Set comprehensions: Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [34]:
from math import sqrt
print({int(sqrt(x)) for x in range(30)})

{0, 1, 2, 3, 4, 5}


Manipulate sets

In [35]:
st = {1, 2, 3, 4, 5}

# intersection
print(st & {1, 3, 5, 7})

# union
print(st | {1, 3, 5, 7})

# diff
print(st - {1, 3, 5, 7})

# union - intersection
print(st ^ {1, 3, 5, 7})

# include
print(st >= {1, 2, 3})

{1, 3, 5}
{1, 2, 3, 4, 5, 7}
{2, 4}
{2, 4, 7}
True


#### Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [36]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print(type(t))
print(d[t])       
print(d[(1, 2)])

<class 'tuple'>
5
1


In [37]:
t[0] = 1

TypeError: 'tuple' object does not support item assignment

## Conditionals

In [39]:
x = 10

if 9 <= x <= 11:
    print('Bravo! I could use chanined comparison.')

Bravo! I could use chanined comparison.


## Loops

In [40]:
import random

cand = [random.randint(2, 20) for _ in range(10)]
#for 循环正常执行结束后，else 语句里面的内容也会正常执行。当 for 循环被 break 中断后，其后的 else 语句就不执行了。
# pick out prime numbers using for..else..
for val in cand:
    for i in range(2, val, 1):
        if val % i == 0:
            print(f'{val} is not a prime!')
            break
    else:
        print(f'{val} is a prime!')

5 is a prime!
20 is not a prime!
11 is a prime!
10 is not a prime!
4 is not a prime!
6 is not a prime!
19 is a prime!
8 is not a prime!
3 is a prime!
20 is not a prime!


## Functions

Python functions are defined using the `def` keyword. For example:

In [41]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [43]:
f = lambda x: x+1

list_ = ['1', '2', '3', '4']
# [1, 2, 3, 4]
f_list_ = list(map(lambda x: x+'0', list_))
print(f_list_)

['10', '20', '30', '40']


We will often define functions to take optional keyword arguments, like this:

In [44]:
def hello(loud=False, name=3218):
    if loud:
        print('HELLO, %s' % name.upper())
    else:
        print('Hello, %s!' % name)

hello(name='Bob')
hello(name='Fred', loud=True)

Hello, Bob!
HELLO, FRED


### Do your functions have _freestyle_?

In [45]:
def f(*args, **kwargs):
    for i in args:
        print(i)
    for key, val in kwargs.items():
        print(f'{key}: {val}')

f(1, 2, 4, a=3)

# this also works
f(1, 3, 5, 7, you='have', done='a', good='job')

1
2
4
a: 3
1
3
5
7
you: have
done: a
good: job


### Check what you've got in a function

In [46]:
def func(list_):
    if not isinstance(list_, list):
        print('This is not list, instead we got {}'.format(type(list_)))
    else:
        print('Awesome! We got a list.')

func([1, 2, 3, 4])

func(1234)

Awesome! We got a list.
This is not list, instead we got <class 'int'>


## Classes

The syntax for defining classes in Python is straightforward:

In [47]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable
        self.height = 172

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
h = Greeter('Henry')
h.greet()
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Henry
Hello, Fred
HELLO, FRED!


# Numpy

NumPy, short for Numerical Python, is one of the most important foundational packages for numerical computing in Python. Most computational packages providing scientific functionality use NumPy’s array objects as the lingua franca for data exchange.

We are going to cover these topics in Numpy:

- Initialization
    
- Indexing
    
- Functions

### Numpy Arrays vs. Python Lists?

1. Why the need for numpy arrays?  Can't we just use Python lists?
2. Iterating over numpy arrays is slow. **Slicing is faster**

Array vs. List

From previous slides we know that Python lists may contain items of different types. This flexibility comes at a price: Python lists store *pointers* to memory locations.  On the other hand, numpy arrays are typed, where the default type is floating point.  Because of this, the system knows how much memory to allocate, and if you ask for an array of size 100, it will allocate one hundred contiguous spots in memory, where the size of each spot is based on the type.  This makes access extremely fast.
    
If you want to know more, we will suggest that you read from [Jake Vanderplas's Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/). You will find that book an incredible resource for this class.

BUT, **iteration slows things down again**. In general you should not access numpy array elements by iteration.  This is because of type conversion.  Numpy stores integers and floating points in C-language format.  When you operate on array elements through iteration, Python needs to convert that element to a Python int or float, which is a more complex beast (a `struct` in C jargon).  This has a cost.

cint vs. pyint

Why is slicing faster? The reason is technical: slicing provides a view onto the memory occupied by a numpy array, instead of creating a new array. That is the reason the code above this cell works nicely as well. However, if you iterate over a slice, then you have gone back to the slow access.

By contrast, functions such as `np.dot` are **implemented at C-level**, do not do this type conversion, and access contiguous memory. If you want this kind of access in Python, use the struct module or Cython. Indeed many fast algorithms in numpy, pandas, and C are either implemented at the C-level, or employ Cython.

To use Numpy, we first need to import the `numpy` package:

In [48]:
import numpy as np

## Initialization

One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.

In [49]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1) # Create a rank 1 array
print(arr1)
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] 
arr2 = np.array(data2) # Create a rank 2 array
print(arr2)

[6.  7.5 8.  0.  1. ]
[[1 2 3 4]
 [5 6 7 8]]


In [50]:
print(arr2.ndim)
print(arr2.shape)
print(arr1.dtype,arr2.dtype)

2
(2, 4)
float64 int32


Numpy also provides many functions to create arrays:

In [51]:
a = np.zeros(10)
b = np.zeros((3, 6))
# Create an array of all zeros
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [52]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [53]:
c = np.full((2,2), 7) # Create a constant array
print(c) 

[[7 7]
 [7 7]]


In [54]:
d = np.eye(2)
e = np.identity(2)
# Create a 2x2 identity matrix
print(d)
print(e)

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [55]:
f = np.random.random((2,2)) # Create an array filled with random values
from numpy import random as r # We don't need modual name when we call the function
print(r.random((2, 3)))
print(f)

[[0.59480394 0.75894629 0.62195837]
 [0.60081036 0.69862776 0.19260289]]
[[0.87075042 0.706129  ]
 [0.66617057 0.39165658]]


## Indexing

NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists

In [56]:
import numpy as np

arr1 = np.arange(10)
print(arr1)
arr2 = arr1[5:8]
arr3 = arr1[5:8].copy()
# Create a slice arr2 for arr1
# Create a copy arr3 for arr1
arr2[:] = 12
print(arr2)
print(arr1)

arr3[:] = 11
print(arr3)
print(arr1)


[0 1 2 3 4 5 6 7 8 9]
[12 12 12]
[ 0  1  2  3  4 12 12 12  8  9]
[11 11 11]
[ 0  1  2  3  4 12 12 12  8  9]


Pay attenetion: A slice of an array is a view into the same data, so modifying it will modify the original array. If you still want to copy part of the array, please use .copy()

In multidimensional arrays, if you omit later indices, the returned object will be a lower dimensional ndarray consisting of all the data along the higher dimensions

In [57]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
row_r1 = arr2d[1, :]    # Rank 1 view of the second row of arr2d → lower dimension 
row_r2 = arr2d[1:2, :]  # Rank 2 view of the second row of arr2d
row_r3 = arr2d[[1], :]  # Rank 2 view of the second row of arr2d
print(row_r1, row_r1.shape) 
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[4 5 6] (3,)
[[4 5 6]] (1, 3)
[[4 5 6]] (1, 3)


![title](slicing.PNG)

Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [58]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a.shape)

print(a)

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]


In [59]:
# Mutate one element from each row of a using the indices in b
b = np.array([0, 1, 1])
a[np.arange(3), b] += 10
# Equivalent to a[np.array([0,1,2]),np.array([0,1,1])] += 10
print(a)

[[11  2]
 [ 3 14]
 [ 5 16]]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [60]:
import numpy as np
data = np.random.randn(4, 3)
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
print(data)
print(names)
print(data[names == 'Bob'])
print(data[names == 'Bob',2])

[[ 1.56011578 -0.44705607 -1.29006797]
 [-0.76209537 -0.47415014  0.75214528]
 [-1.70957306 -1.07384614  0.16569791]
 [ 1.91879791 -0.38568817 -2.44781727]]
['Bob' 'Joe' 'Will' 'Bob']
[[ 1.56011578 -0.44705607 -1.29006797]
 [ 1.91879791 -0.38568817 -2.44781727]]
[-1.29006797 -2.44781727]


The Python keywords and and or do not work with boolean arrays. Use & (and) and | (or) instead.

you can either use != or negate the condition using ~

Boolean selection will not fail if the boolean array is not the correct length, so I recommend care when using this feature.

In [61]:
mask = ~((names != 'Joe')& (names != 'Will'))
# We print the row corrseponding to 'Joe' or 'Will'
print(data[mask])

[[-0.76209537 -0.47415014  0.75214528]
 [-1.70957306 -1.07384614  0.16569791]]


## Functions

A universal function, or ufunc, is a function that performs element-wise operations
on data in ndarrays. You can think of them as fast vectorized wrappers for simple
functions that take one or more scalar values and produce one or more scalar results.

In [62]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)
print(x + y)
# print(np.add(x, y))
print(x - y)
# print(np.subtract(x, y))
print(x * y)
# print(np.multiply(x, y))
print(x / y)
# print(np.divide(x, y))
print(np.sqrt(x))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the **dot** function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [63]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9, 10])
w = np.array([11, 12])

print(x.dot(v))
print(np.dot(x, v))
print(v.dot(w))
print(np.dot(v, w))


[29 67]
[29 67]
219
219


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [64]:
x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Here are some basic functions:

![title](ufuncs.png)

![title](binufun1.png)
![title](binufun2.png)

Apart from computing mathematical functions using arrays, we frequently need to **reshape** or otherwise **manipulate** data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [65]:
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [66]:
v = np.array([[1,2,3]])
print(v) 
print(v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]
